export const workbenchGroups = {
  account: ['oop-encapsulation', 'api-contract-invariants'],
  objects: [
    'oop-classes-objects',
    'oop-static-instance-members',
    'shallow-deep-copy',
    'mutability-aliasing',
    'function-arguments',
    'pointer-reference-basics',
    'java-gc-references',
  ],
  lifetime: [
    'stack-vs-heap',
    'variable-scope-lifetime',
    'constructor-initialization',
    'c-malloc-free',
    'c-undefined-behavior',
    'cpp-raii',
    'cpp-virtual-destructor',
    'rust-borrowing-lifetimes',
    'zig-error-union-defer',
  ],
  errors: ['error-handling-models'],
  contracts: [
    'struct-enum-modeling',
    'oop-abstraction',
    'oop-inheritance-composition',
    'oop-interface-abstract-class',
    'generic-programming-basics',
    'null-option-absence',
    'callbacks-function-pointers',
    'java-equals-hashcode',
    'kotlin-null-safety',
  ],
  representation: [
    'type-conversion-casting',
    'array-bounds-slices',
    'floating-point-basics',
    'text-encoding-utf8',
  ],
  hardware: [
    'memory-hierarchy-basic',
    'cache-write-through-back',
    'cache-coherence-basic',
    'cpu-pipeline-hazards',
    'interrupt-vs-polling',
  ],
  structures: [
    'amortized-dynamic-array',
    'linear-search-first',
    'hash-collisions-resizing',
    'binary-search-tree-operations',
    'heap-top-k',
  ],
  traversal: ['binary-tree-level-order', 'graph-dfs', 'topological-sort'],
  sequences: ['merge-sort', 'stack-valid-parentheses', 'backtracking-basics'],
  greedy: ['greedy-basics'],
  dp: ['dynamic-programming-intro', 'dynamic-programming-lcs'],
  kernel: [
    'context-switch',
    'scheduler-starvation-priority',
    'process-vs-thread-resources',
    'interrupt-exception-trap',
    'mutex-vs-semaphore',
    'condition-variable',
    'copy-on-write',
    'file-system-inode',
    'ipc-pipe',
  ],
  network: [
    'nat-basic',
    'tcp-retransmission-rto',
    'tcp-flow-congestion',
    'dns-cache-ttl',
    'http1-keepalive',
    'http2-multiplexing',
    'http-status-codes',
    'cookie-session-token',
    'tls-handshake-basic',
  ],
  database: [
    'database-normalization',
    'composite-index-order',
    'database-index-selectivity',
    'database-join-algorithms',
    'database-mvcc-basic',
    'database-connection-pool',
  ],
  concurrency: ['memory-ordering-visibility', 'race-condition-vs-data-race'],
  delivery: ['message-queue-delivery', 'idempotency-requests', 'cache-consistency-basics'],
  queues: [
    'thread-pool-basics',
    'backpressure-basics',
    'load-balancing-basics',
    'bulkhead-failure-isolation',
  ],
  resilience: ['timeouts-deadlines', 'retry-exponential-backoff', 'circuit-breaker-basics'],
  build: [
    'program-compile-run',
    'module-compile-link',
    'build-artifact-release',
    'dependency-lockfiles',
    'ci-pipeline-basic',
  ],
  git: ['git-branch-merge-rebase', 'git-restore-reset-revert'],
  operations: [
    'unit-integration-e2e-tests',
    'metrics-tracing-basics',
    'performance-profiling-basic',
    'configuration-secrets',
    'deployment-rollback',
    'incident-triage-postmortem',
  ],
  interview: [
    'self-introduction-technical',
    'project-explanation-structure',
    'technical-tradeoffs',
    'debugging-story-evidence',
    'unknown-question-reasoning',
  ],
  dispatch: ['oop-overloading-overriding'],
};

export function workbenchFor(slug) {
  const groups = /** @type {Array<keyof typeof workbenchGroups>} */ (Object.keys(workbenchGroups));
  return groups.find((group) => workbenchGroups[group].includes(slug));
}
